CREATE TABLE ArtistAccount
(
	ArtistAccountID NUMERIC IDENTITY (1,1) NOT NULL
		CONSTRAINT PK_ArtistAccountID PRIMARY KEY
	, Email VARCHAR (255) NOT NULL
	, FirstName VARCHAR (255) NOT NULL
	, LastName VARCHAR (255) NOT NULL
	, Password VARCHAR (255) NOT NULL
	, MiddleName VARCHAR (255) NOT NULL
	, DateOfBirth VARCHAR (255) NOT NULL
	, Country VARCHAR (255) NOT NULL
	, Baranggay VARCHAR (255) NOT NULL
	, Region VARCHAR (255) NOT NULL
	, HomeNumber VARCHAR (255) NOT NULL
	, PhoneNumber VARCHAR (255) NOT NULL
	, City VARCHAR (255) NOT NULL
	, PostalCode NUMERIC (20) NOT NULL
	, Gender VARCHAR (20) NOT NULL
	, UserName VARCHAR (255) NOT NULL
	, Street VARCHAR (255) NOT NULL
	, DefaultPic VARCHAR (255) NOT NULL
	, ID NUMERIC
	, softdelete NUMERIC
	, ValidIDPic VARCHAR
);