CREATE TABLE Wish
(
	Wish_ID NUMERIC IDENTITY (1,1) NOT NULL
		CONSTRAINT PK_Wish_ID PRIMARY KEY
	, AccountID NUMERIC 
	, Art_ID NUMERIC 
	, Art_Name VARCHAR (255) 
	, Art_Image VARCHAR (255)
	, Artist VARCHAR (255)
)